### ISSUE TITLE
NoSuchMethodError on opentracing-grpc 0.2.0

### ISSUE THREAD

**Issue by thloml** [opentracing-contrib/java-grpc#49]
I'm using opentracing-grpc0.2.0 with Grpc clinet, I follow your wikis but got this error, here is my code:
```
@Resource
brave.Tracing tracing;
public GRPCHelloClient(String ip){
		channel = ManagedChannelBuilder.forAddress(ip,50052) 
                .usePlaintext(true) 
                .build();
io.opentracing.Tracer openTracer = BraveTracer.create(tracing);
		TracingClientInterceptor tracingInterceptor = TracingClientInterceptor.newBuilder().withTracer(tracer).build();
		helloStub = HelloGrpc.newBlockingStub(tracingInterceptor.intercept(channel));
	}
public String hello(String name) {
		Builder builder = HelloRequest.newBuilder();
		builder.setName(name);
		HelloRequest request = builder.build();
		HelloReply reply = helloStub.sayHello(request);
		return reply.getMessage();
	}
```
and when call hello(), error occurred;
```
java.lang.NoSuchMethodError: io.opentracing.ScopeManager.activate(Lio/opentracing/Span;)Lio/opentracing/Scope;
	at io.opentracing.contrib.grpc.TracingClientInterceptor.interceptCall(TracingClientInterceptor.java:103) ~[opentracing-grpc-0.2.0.jar:na]
	at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156) ~[grpc-core-1.17.1.jar:1.17.1]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:125) ~[grpc-stub-1.17.1.jar:1.17.1]
	at proto.HelloGrpc$HelloBlockingStub.sayHello(HelloGrpc.java:156) ~[classes/:na]
	at com.neo.service.GRPCHelloClient.hello(GRPCHelloClient.java:36) ~[classes/:na]
	at com.neo.controller.HelloController.grpc(HelloController.java:53) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) ~[spring-web-5.0.13.RELEASE.jar:5.0.13.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-5.0.13.RELEASE.jar:5.0.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.0.13.RELEASE.jar:5.0.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894) ~[spring-webmvc-5.0.13.RELEASE.jar:5.0.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800) ~[spring-webmvc-5.0.13.RELEASE.jar:5.0.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.0.13.RELEASE.jar:5.0.13.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) ~[spring-webmvc-5.0.13.RELEASE.jar:5.0.13.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) ~[spring-webmvc-5.0.13.RELEASE.jar:5.0.13.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:981) ~[spring-webmvc-5.0.13.RELEASE.jar:5.0.13.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:873) ~[spring-webmvc-5.0.13.RELEASE.jar:5.0.13.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) ~[tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:858) ~[spring-webmvc-5.0.13.RELEASE.jar:5.0.13.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.39.jar:8.5.39]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-5.0.13.RELEASE.jar:5.0.13.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.13.RELEASE.jar:5.0.13.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) ~[spring-web-5.0.13.RELEASE.jar:5.0.13.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.13.RELEASE.jar:5.0.13.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) ~[spring-web-5.0.13.RELEASE.jar:5.0.13.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.13.RELEASE.jar:5.0.13.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.springframework.cloud.sleuth.instrument.web.ExceptionLoggingFilter.doFilter(ExceptionLoggingFilter.java:48) ~[spring-cloud-sleuth-core-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.39.jar:8.5.39]
	at brave.servlet.TracingFilter.doFilter(TracingFilter.java:86) ~[brave-instrumentation-servlet-5.1.0.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) ~[spring-web-5.0.13.RELEASE.jar:5.0.13.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.13.RELEASE.jar:5.0.13.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) ~[tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) [tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137) [tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798) [tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806) [tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) [tomcat-embed-core-8.5.39.jar:8.5.39]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.39.jar:8.5.39]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.39.jar:8.5.39]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
```
and my pom.xml
```
               <dependency>
		    <groupId>io.opentracing.contrib</groupId>
		    <artifactId>opentracing-spring-cloud-starter</artifactId>
		    <version>0.2.6</version>
		</dependency>
		<dependency>
			<groupId>io.opentracing.contrib</groupId>
			<artifactId>opentracing-spring-zipkin-web-starter</artifactId>
			<version>0.2.0</version>
		</dependency> 
		<dependency>
		    <groupId>io.opentracing.contrib</groupId>
		    <artifactId>opentracing-grpc</artifactId>
		    <version>0.2.0</version>
		</dependency>
		<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-zipkin</artifactId>
        </dependency>
```
Am I using the wrong version of io.opentracing.contrib components?

**Comment by malafeev** [comment]
yes, please update them to latest versions

**Comment by thloml** [comment]
I've updated opentracing-spring-cloud-starter from 0.2.6 to 0.3.7 bug got the same error

**Comment by thloml** [comment]
the last line:
```
[INFO] | +- org.springframework.cloud:spring-cloud-starter-openfeign:jar:2.0.0.RELEASE:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-openfeign-core:jar:2.0.0.RELEASE:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-commons:jar:2.0.0.RELEASE:compile
[INFO] |  |  \- org.springframework.security:spring-security-crypto:jar:5.0.12.RELEASE:compile
[INFO] |  +- io.github.openfeign:feign-core:jar:9.5.1:compile
[INFO] |  +- io.github.openfeign:feign-slf4j:jar:9.5.1:compile
[INFO] |  +- io.github.openfeign:feign-hystrix:jar:9.5.1:compile
[INFO] |  |  \- com.netflix.hystrix:hystrix-core:jar:1.5.12:compile
[INFO] |  |     \- org.hdrhistogram:HdrHistogram:jar:2.1.9:compile
[INFO] |  \- io.github.openfeign:feign-java8:jar:9.5.1:compile
[INFO] +- io.opentracing.contrib:opentracing-spring-cloud-starter:jar:0.3.7:compile
[INFO] |  +- io.opentracing.contrib:opentracing-spring-cloud-core:jar:0.3.7:compile
[INFO] |  |  +- io.opentracing.contrib:opentracing-spring-tracer-configuration-starter:jar:0.2.0:compile
[INFO] |  |  \- io.opentracing.contrib:opentracing-concurrent:jar:0.3.0:compile
[INFO] |  +- io.opentracing.contrib:opentracing-spring-web-starter:jar:2.1.1:compile
[INFO] |  |  +- io.opentracing.contrib:opentracing-spring-web:jar:2.1.1:compile
[INFO] |  |  |  \- io.opentracing.contrib:opentracing-web-servlet-filter:jar:0.3.0:compile
[INFO] |  |  \- io.opentracing.contrib:opentracing-tracerresolver:jar:0.1.6:compile
[INFO] |  +- io.opentracing.contrib:opentracing-spring-messaging-starter:jar:0.1.2:compile
[INFO] |  |  \- io.opentracing.contrib:opentracing-spring-messaging:jar:0.1.2:compile
[INFO] |  +- io.opentracing.contrib:opentracing-spring-rabbitmq-starter:jar:2.0.5:compile
[INFO] |  |  \- io.opentracing.contrib:opentracing-spring-rabbitmq:jar:2.0.5:compile
[INFO] |  +- io.opentracing.contrib:opentracing-spring-cloud-jdbc-starter:jar:0.3.7:compile
[INFO] |  |  \- io.opentracing.contrib:opentracing-jdbc:jar:0.1.1:compile
[INFO] |  +- io.opentracing.contrib:opentracing-spring-cloud-jms-starter:jar:0.3.7:compile
[INFO] |  |  +- io.opentracing.contrib:opentracing-jms-spring:jar:0.1.0:compile
[INFO] |  |  +- io.opentracing.contrib:opentracing-jms-1:jar:0.1.0:compile
[INFO] |  |  \- io.opentracing.contrib:opentracing-jms-common:jar:0.1.0:compile
[INFO] |  +- io.opentracing.contrib:opentracing-spring-cloud-feign-starter:jar:0.3.7:compile
[INFO] |  |  +- io.github.openfeign.opentracing:feign-opentracing:jar:0.3.0:compile
[INFO] |  |  \- io.github.openfeign.opentracing:feign-hystrix-opentracing:jar:0.3.0:compile
[INFO] |  +- io.opentracing.contrib:opentracing-spring-cloud-hystrix-starter:jar:0.3.7:compile
[INFO] |  +- io.opentracing.contrib:opentracing-spring-cloud-reactor-starter:jar:0.3.7:compile
[INFO] |  |  \- io.opentracing.contrib:opentracing-reactor:jar:0.1.0:compile
[INFO] |  +- io.opentracing.contrib:opentracing-spring-cloud-rxjava-starter:jar:0.3.7:compile
[INFO] |  |  \- io.opentracing.contrib:opentracing-rxjava-1:jar:0.1.0:compile
[INFO] |  +- io.opentracing.contrib:opentracing-spring-cloud-redis-starter:jar:0.3.7:compile
[INFO] |  |  +- io.opentracing.contrib:opentracing-redis-spring-data2:jar:0.1.2:compile
[INFO] |  |  \- io.opentracing.contrib:opentracing-redis-common:jar:0.1.2:compile
[INFO] |  +- io.opentracing.contrib:opentracing-spring-cloud-mongo-starter:jar:0.3.7:compile
[INFO] |  |  +- io.opentracing.contrib:opentracing-mongo-driver:jar:0.1.2:compile
[INFO] |  |  \- io.opentracing.contrib:opentracing-mongo-common:jar:0.1.2:compile
[INFO] |  +- io.opentracing.contrib:opentracing-spring-cloud-websocket-starter:jar:0.3.7:compile
[INFO] |  +- io.opentracing.contrib:opentracing-spring-cloud-zuul-starter:jar:0.3.7:compile
[INFO] |  \- io.opentracing:opentracing-api:jar:0.32.0:compile

```

**Comment by malafeev** [comment]
how about `opentracing-spring-zipkin-web-starter`? it can bring opentracing-api older.

**Comment by thloml** [comment]
I didn't find opentracing-api in `opentracing-spring-zipkin-web-starter`
```
[INFO] +- io.opentracing.contrib:opentracing-spring-zipkin-web-starter:jar:0.2.0:compile
[INFO] |  \- io.opentracing.contrib:opentracing-spring-zipkin-starter:jar:0.2.0:compile
[INFO] |     +- io.opentracing.brave:brave-opentracing:jar:0.31.1:compile
[INFO] |     |  +- io.zipkin.brave:brave:jar:5.1.0:compile
[INFO] |     |  \- io.zipkin.brave:brave-tests:jar:5.1.0:compile
[INFO] |     \- io.zipkin.reporter2:zipkin-sender-okhttp3:jar:2.6.0:compile
[INFO] |        \- com.squareup.okhttp3:okhttp:jar:3.8.1:compile
[INFO] |           \- com.squareup.okio:okio:jar:1.13.0:compile
```

**Comment by malafeev** [comment]
```
 +- io.opentracing.contrib:opentracing-spring-zipkin-web-starter:jar:0.2.0:compile
[INFO] |  +- io.opentracing.contrib:opentracing-spring-zipkin-starter:jar:0.2.0:compile
[INFO] |  |  +- io.opentracing.contrib:opentracing-spring-tracer-configuration-starter:jar:0.1.0:compile
[INFO] |  |  |  +- io.opentracing:opentracing-noop:jar:0.31.0:compile
[INFO] |  |  |  +- io.opentracing:opentracing-util:jar:0.31.0:compile
[INFO] |  |  |  \- org.springframework:spring-core:jar:4.3.16.RELEASE:compile
[INFO] |  |  +- io.opentracing:opentracing-api:jar:0.31.0:compile
[INFO] |  |  +- io.opentracing.brave:brave-opentracing:jar:0.31.3:compile
[INFO] |  |  |  \- io.zipkin.brave:brave:jar:5.1.4:compile
[INFO] |  |  \- io.zipkin.reporter2:zipkin-sender-okhttp3:jar:2.6.0:compile
[INFO] |  |     +- io.zipkin.reporter2:zipkin-reporter:jar:2.6.0:compile
[INFO] |  |     +- com.squareup.okhttp3:okhttp:jar:3.10.0:compile
[INFO] |  |     |  \- com.squareup.okio:okio:jar:1.14.0:compile
[INFO] |  |     \- io.zipkin.zipkin2:zipkin:jar:2.8.1:compile
```
it has `o.opentracing:opentracing-api:jar:0.31.0:compile`

**Comment by malafeev** [comment]
I understand, but `BraveTracer`, `BraveScopeManager` which are used in your app implement opentracing-api 0.31.0. That's why you see `NoSuchMethodError`

**Comment by malafeev** [comment]
PR https://github.com/opentracing-contrib/java-spring-zipkin/pull/9 is still open

**Comment by thloml** [comment]
okey, i just waiting till new version released, thank you so much!
