### ISSUE TITLE
ClassCastException for TextMapExtractAdapter in version 0.2.0

### ISSUE THREAD

**Issue by deveshbajpai19** [opentracing-contrib/java-grpc#52]
I'm facing the following exception for io.opentracing.propagation.TextMapExtractAdapter when it tries to extract the context in the Server tracing interception. 

I believe this is due to the fact that this adapter doesn't implement TextMap directly, and hence the extract() API cannot cast it properly. 

```2020-05-24T20:44:47,671 [t=<CUSTOM SERVICE NAME HIDDEN>, WARN,log=i.j.i.PropagationRegistry$ExceptionCatchingExtractorDecorator] () () - Error when extracting SpanContext from carrier. Handling gracefully.
java.lang.ClassCastException: class io.opentracing.propagation.TextMapExtractAdapter cannot be cast to class io.opentracing.propagation.TextMap (io.opentracing.propagation.TextMapExtractAdapter and io.opentracing.propagation.TextMap are in unnamed module of loader 'app')
	at io.jaegertracing.internal.propagation.TextMapCodec.extract(TextMapCodec.java:37) ~[jaeger-core-1.2.0.jar:1.2.0]
	at io.jaegertracing.internal.PropagationRegistry$ExceptionCatchingExtractorDecorator.extract(PropagationRegistry.java:57) [jaeger-core-1.2.0.jar:1.2.0]
	at io.jaegertracing.internal.JaegerTracer.extract(JaegerTracer.java:220) [jaeger-core-1.2.0.jar:1.2.0]
	at io.jaegertracing.internal.JaegerTracer.extract(JaegerTracer.java:63) [jaeger-core-1.2.0.jar:1.2.0]
	at io.opentracing.contrib.ServerTracingInterceptor.getSpanFromHeaders(ServerTracingInterceptor.java:151) [grpc-opentracing-0.2.0.jar:?]
	at io.opentracing.contrib.ServerTracingInterceptor.interceptCall(ServerTracingInterceptor.java:92) [grpc-opentracing-0.2.0.jar:?]
	at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:229) [grpc-api-1.21.0.jar:1.21.0]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:610) [grpc-core-1.21.0.jar:1.21.0]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startCall(ServerImpl.java:590) [grpc-core-1.21.0.jar:1.21.0]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$1900(ServerImpl.java:410) [grpc-core-1.21.0.jar:1.21.0]
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1StreamCreated.runInContext(ServerImpl.java:526) [grpc-core-1.21.0.jar:1.21.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.21.0.jar:1.21.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.21.0.jar:1.21.0]
	at <CUSTOM SERVICE CLASS NAME>:25) [concurrent/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]```


Please advise how to mitigate this issue.

**Comment by yurishkuro** [comment]
This might be an issue with the Jaeger client where instead of expecting TextMapExtract it expects the full TextMap interface (which was the only option in the earlier versions of OpenTracing API).

**Comment by deveshbajpai19** [comment]
So do I need to update the Jaeger client dependencies? 
I'm using the following:
```
    implementation 'io.opentracing:opentracing-api:0.32.0'
    implementation 'io.jaegertracing:jaeger-client:1.2.0'
    implementation group: 'io.opentracing.contrib', name: 'grpc-opentracing', version: '0.2.0'```

**Comment by yurishkuro** [comment]
are you using the right version of THIS library? Your stacktrace shows `ServerTracingInterceptor`, which is not in this repo.

**Comment by deveshbajpai19** [comment]
Okay so the problem was a wrong dependency. 
Along with io.opentracing.contrib:opentracing-grpc (which is generated from this repo), there is also  io.opentracing.contrib:grpc-opentracing. That had the class ServerTracingInterceptor which caused the class-cast exception. 

Thanks @yurishkuro for pointing out. I'll close this issue.
